# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: sa-east-1
          role-to-assume: ${{ secrets.IAM_ROLE }}
          role-session-name: DeploySession

      - name: Zip function
        run: zip function.zip main.rb

      - name: Send to AWS
        run: aws lambda update-function-code --function-name ${{ secrets.LAMBDA_NAME }} --zip-file fileb://function.zip
